travis: update to bionic
The curl MIME API was added to curl version 7.56.0.
So, bump to 7.58.0 with bionic.

Fixes:

 In file included from /usr/include/curl/curl.h:2402:0,
                 from handlers/swuforward_handler.h:11,
                 from handlers/swuforward_handler.c:38:
 handlers/swuforward_handler.c:175:43: error: ‘CURLOPT_MIMEPOST’ undeclared (first use in this function)
      (curl_easy_setopt(conn->curl_handle, CURLOPT_MIMEPOST,

Also add:
 - liburiparser
 - libwebsocket (fetched from github)

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
Acked-by: Stefano Babic <sbabic@denx.de>