Fix warning due to close() in chain_handler
Depending on configuration, close() prototype is missing:

handlers/chain_handler.c:42:17: warning: implicit declaration of function ‘close’

Signed-off-by: Stefano Babic <sbabic@denx.de>