Fix build without MTD support
handlers/raw_handler and corelib/installer does not need flash.h.
corelib/stream_interface and core/swupdate should include flash.h only
conditionally.

This fixes build errors if HAVE_MTD is not set and libmtd is not available:

In file included from include/swupdate.h:25:0,
                 from handlers/raw_handler.c:33:
include/flash.h:26:24: fatal error: mtd/libmtd.h: No such file or directory

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>