Revert "Fix some compiler warnings if !CONFIG_HASH_VERIFY"
This reverts commit 15a08c0081c5f2b012a5418bcf8403d557337141.

Commit introduces build error if openssl is not used.

include/sslapi.h:96:19: error: conflicting types for ‘swupdate_HASH_update’
 static inline int swupdate_HASH_update(struct swupdate_digest *dgst,

Signed-off-by: Stefano Babic <sbabic@denx.de>
CC: Christian Storm <christian.storm@siemens.com>