ipc: add missing unistd.h include
musl requires unistd.h to be included for close() as specified by POSIX.

This always printed a warning and has become and error since gcc 14:

ipc/network_ipc-if.c: In function 'inst_wait_for_complete':
ipc/network_ipc-if.c:74:17: error: implicit declaration of function 'close'; did you mean 'clone'? [-Wimplicit-function-declaration]
   74 |                 close(*progressfd);
      |                 ^~~~~
      |                 clone

Signed-off-by: AFIQE ANUAR <afiqe.anuar@atmark-techno.com>
Signed-off-by: Dominique Martinet <dominique.martinet@atmark-techno.com>